#include "Combat/Core/CombatTags.h"

namespace CombatTags
{
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Alive, "State.Alive", "单位处于存活状态")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Dying, "State.Dying", "单位正在执行死亡结算")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Dead, "State.Dead", "单位已经死亡")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Respawning, "State.Respawning", "单位正在执行复活流程")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Stunned, "State.Stunned", "单位被眩晕，禁止移动、攻击和普通技能")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Silenced, "State.Silenced", "单位被沉默，禁止普通技能")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Rooted, "State.Rooted", "单位被缠绕，禁止自主移动")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Disarmed, "State.Disarmed", "单位被缴械，禁止普通攻击")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Hexed, "State.Hexed", "单位处于妖术控制状态")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Invisible, "State.Invisible", "单位处于隐身状态")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Invulnerable, "State.Invulnerable", "单位处于无敌状态")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_OutOfGame, "State.OutOfGame", "单位暂时移出战斗")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_MagicImmune, "State.MagicImmune", "单位具有魔法免疫")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Untargetable, "State.Untargetable", "单位不可被常规目标选择")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_NoUnitCollision, "State.NoUnitCollision", "单位忽略与其他单位的碰撞")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_NoHealthBar, "State.NoHealthBar", "单位不显示生命条")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Frozen, "State.Frozen", "单位处于冻结状态")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_SpellBlock, "State.SpellBlock", "单位拥有可消耗的技能格挡")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Broken, "State.Broken", "单位处于破坏状态，可破坏的被动行为暂停")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_DebuffImmune, "State.DebuffImmune", "单位免疫新施加的减益 Modifier")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_DispelImmune, "State.DispelImmune", "单位免疫驱散操作")

	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Behavior_NoTarget, "Ability.Behavior.NoTarget", "技能不需要目标")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Behavior_UnitTarget, "Ability.Behavior.UnitTarget", "技能需要单位目标")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Behavior_PointTarget, "Ability.Behavior.PointTarget", "技能需要世界位置目标")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Behavior_Passive, "Ability.Behavior.Passive", "技能为被动技能")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Behavior_Channelled, "Ability.Behavior.Channelled", "技能包含持续施法阶段")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Behavior_AoE, "Ability.Behavior.AoE", "技能使用范围目标查询")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Behavior_Attack, "Ability.Behavior.Attack", "技能参与普通攻击或法球流程")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Behavior_AutoCast, "Ability.Behavior.AutoCast", "技能支持自动施法开关")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Behavior_IgnoreSilence, "Ability.Behavior.IgnoreSilence", "技能可在沉默状态下使用")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Behavior_IgnoreMagicImmune, "Ability.Behavior.IgnoreMagicImmune", "技能目标校验忽略魔法免疫")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Behavior_IgnoreUntargetable, "Ability.Behavior.IgnoreUntargetable", "技能目标校验忽略不可选中状态")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Behavior_SpellBlockable, "Ability.Behavior.SpellBlockable", "技能可在 SpellStarted 提交后被技能格挡")

	UE_DEFINE_GAMEPLAY_TAG_COMMENT(TargetTeam_None, "TargetTeam.None", "不进行单位阵营选择")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(TargetTeam_Enemy, "TargetTeam.Enemy", "只允许敌对单位")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(TargetTeam_Friendly, "TargetTeam.Friendly", "只允许友方单位")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(TargetTeam_Both, "TargetTeam.Both", "允许友方和敌对单位")

	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Damage_Type_Physical, "Damage.Type.Physical", "物理伤害，按护甲结算")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Damage_Type_Magical, "Damage.Type.Magical", "魔法伤害，按魔法抗性结算")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Damage_Type_Pure, "Damage.Type.Pure", "纯粹伤害，不经过护甲或魔法抗性")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Damage_Flag_BypassMagicImmune, "Damage.Flag.BypassMagicImmune", "本次伤害忽略魔法免疫")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Damage_Flag_HPLoss, "Damage.Flag.HPLoss", "本次伤害按生命移除语义结算")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Damage_Flag_NoSpellAmplification, "Damage.Flag.NoSpellAmplification", "本次伤害不受技能伤害增幅影响")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Damage_Flag_Reflection, "Damage.Flag.Reflection", "本次伤害来自反射，供防递归与统计使用")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Damage_Flag_NoLifesteal, "Damage.Flag.NoLifesteal", "本次伤害不触发吸血")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Damage_Flag_NoCrit, "Damage.Flag.NoCrit", "本次伤害不允许暴击")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Data_Damage_Final, "Data.Damage.Final", "GAS Execution 写入的最终伤害载荷")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Data_Heal_Final, "Data.Heal.Final", "GAS Execution 写入的最终治疗载荷")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Cue_Combat, "Cue.Combat", "Combat GameplayCue 根标签")

	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_DamageApplied, "Event.Combat.DamageApplied", "伤害事务完成并应用真实伤害")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_HealApplied, "Event.Combat.HealApplied", "治疗事务完成并应用真实治疗")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_ModifierApplied, "Event.Combat.ModifierApplied", "Modifier 成功创建或刷新")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_ModifierRemoved, "Event.Combat.ModifierRemoved", "Modifier 已从目标移除")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_UnitDeath, "Event.Combat.UnitDeath", "单位完成进入死亡状态")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_UnitRespawned, "Event.Combat.UnitRespawned", "单位完成复活并重新存活")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_TeamChanged, "Event.Combat.TeamChanged", "单位阵营发生权威变更")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_AbilityGranted, "Event.Combat.AbilityGranted", "Ability 已授予单位")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_AbilityRemoved, "Event.Combat.AbilityRemoved", "Ability 已从单位移除")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_AbilityLevelChanged, "Event.Combat.AbilityLevelChanged", "Ability 权威等级发生变更")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_AutoCastChanged, "Event.Combat.AutoCastChanged", "Ability 自动施法状态发生变更")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_AbilityCastStarted, "Event.Combat.AbilityCastStarted", "Ability 已开始前摇")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_AbilitySpellStarted, "Event.Combat.AbilitySpellStarted", "Ability 已到达 SpellStarted 提交点")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_AbilityChannelEnded, "Event.Combat.AbilityChannelEnded", "Ability 引导阶段已经结束")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_AbilityOrderReleased, "Event.Combat.AbilityOrderReleased", "Ability 已释放关联的 Order")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_AbilityInterrupted, "Event.Combat.AbilityInterrupted", "Ability 已被中断")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_AbilityEnded, "Event.Combat.AbilityEnded", "Ability 激活已经结束")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_AbilityActionFailed, "Event.Combat.AbilityActionFailed", "Ability 公共动作执行失败")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_OrderStateChanged, "Event.Combat.OrderStateChanged", "单位 Order 状态发生变更")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_AttackLaunched, "Event.Combat.AttackLaunched", "普通攻击已发射或提交命中流程")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_AttackLanded, "Event.Combat.AttackLanded", "普通攻击已经命中并完成结算")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_AttackFailed, "Event.Combat.AttackFailed", "普通攻击启动或命中失败")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_ProjectileSpawned, "Event.Combat.ProjectileSpawned", "战斗弹体已在服务器生成")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_ProjectileHit, "Event.Combat.ProjectileHit", "战斗弹体命中合法目标或世界")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_ProjectileFinished, "Event.Combat.ProjectileFinished", "战斗弹体已经结束")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_ThinkerPulse, "Event.Combat.ThinkerPulse", "Thinker 完成一次逻辑脉冲")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_ThinkerFinished, "Event.Combat.ThinkerFinished", "Thinker 已经结束")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_MotionStarted, "Event.Combat.MotionStarted", "强制位移已经开始")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_MotionFinished, "Event.Combat.MotionFinished", "强制位移已经结束")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_AbilitySpellBlocked, "Event.Combat.AbilitySpellBlocked", "Ability 在 SpellStarted 后被技能格挡")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_AuraStarted, "Event.Combat.AuraStarted", "Aura 已开始服务器协调")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_AuraReconciled, "Event.Combat.AuraReconciled", "Aura 已完成一次目标与子 Modifier 协调")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_AuraFinished, "Event.Combat.AuraFinished", "Aura 已经结束并清理子 Modifier")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Combat_BlockerChanged, "Event.Combat.BlockerChanged", "战斗物理阻挡物的生命周期发生变更")

	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Authority, "Combat.Failure.Authority", "操作失败：当前上下文没有服务器权威")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_InvalidNumber, "Combat.Failure.InvalidNumber", "操作失败：输入包含非法或非有限数值")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_ActionUnsupported, "Combat.Failure.ActionUnsupported", "操作失败：当前动作类型不受支持")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Target_Invalid, "Combat.Failure.Target.Invalid", "目标失败：目标对象无效")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Target_TeamInvalid, "Combat.Failure.Target.TeamInvalid", "目标失败：阵营关系不符合规则")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Target_SelfNotAllowed, "Combat.Failure.Target.SelfNotAllowed", "目标失败：规则不允许选择自身")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Target_FriendlyNotAllowed, "Combat.Failure.Target.FriendlyNotAllowed", "目标失败：规则不允许友方单位")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Target_HostileNotAllowed, "Combat.Failure.Target.HostileNotAllowed", "目标失败：规则不允许敌对单位")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Target_NeutralNotAllowed, "Combat.Failure.Target.NeutralNotAllowed", "目标失败：规则不允许中立单位")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Target_Dying, "Combat.Failure.Target.Dying", "目标失败：目标正在死亡结算")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Target_Dead, "Combat.Failure.Target.Dead", "目标失败：目标已经死亡")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Target_Respawning, "Combat.Failure.Target.Respawning", "目标失败：目标正在复活")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Target_Untargetable, "Combat.Failure.Target.Untargetable", "目标失败：目标不可被选择")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Target_OutOfGame, "Combat.Failure.Target.OutOfGame", "目标失败：目标已移出战斗")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Target_Invulnerable, "Combat.Failure.Target.Invulnerable", "目标失败：目标处于无敌状态")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Target_MagicImmune, "Combat.Failure.Target.MagicImmune", "目标失败：目标具有魔法免疫")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Target_OutOfRange, "Combat.Failure.Target.OutOfRange", "目标失败：目标超出允许距离")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Target_LocationInvalid, "Combat.Failure.Target.LocationInvalid", "目标失败：目标位置无效")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Target_LineOfSightBlocked, "Combat.Failure.Target.LineOfSightBlocked", "目标失败：视线被阻挡")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Life_NotAlive, "Combat.Failure.Life.NotAlive", "生命流程失败：单位当前不处于存活状态")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Life_InvalidTransition, "Combat.Failure.Life.InvalidTransition", "生命流程失败：状态迁移不合法")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Ability_DuplicateDefinition, "Combat.Failure.Ability.DuplicateDefinition", "技能失败：同一定义已经授予")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Ability_InvalidLevel, "Combat.Failure.Ability.InvalidLevel", "技能失败：技能等级无效")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Ability_NotGranted, "Combat.Failure.Ability.NotGranted", "技能失败：技能尚未授予")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Ability_InvalidTargetData, "Combat.Failure.Ability.InvalidTargetData", "技能失败：目标数据与技能模式不匹配")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Ability_Cost, "Combat.Failure.Ability.Cost", "技能失败：资源不足或费用提交失败")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Ability_Cooldown, "Combat.Failure.Ability.Cooldown", "技能失败：技能仍在冷却中")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Ability_CommitFailed, "Combat.Failure.Ability.CommitFailed", "技能失败：费用或冷却提交失败")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Ability_AlreadyActive, "Combat.Failure.Ability.AlreadyActive", "技能失败：技能实例已经激活")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Ability_UnitStateBlocked, "Combat.Failure.Ability.UnitStateBlocked", "技能失败：单位当前状态禁止施法")

	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Order_Failure_Cancelled, "Order.Failure.Cancelled", "命令失败：命令已被显式取消")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Order_Failure_QueueFull, "Order.Failure.QueueFull", "命令失败：命令队列已满")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Order_Failure_PathFailed, "Order.Failure.PathFailed", "命令失败：寻路请求失败")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Order_Failure_Blocked, "Order.Failure.Blocked", "命令失败：路径或动作被阻挡")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Order_Failure_AbilityRejected, "Order.Failure.AbilityRejected", "命令失败：技能请求被拒绝")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Order_Failure_UnitStateBlocked, "Order.Failure.UnitStateBlocked", "命令失败：单位状态禁止执行")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Order_Failure_TargetInvalid, "Order.Failure.TargetInvalid", "命令失败：目标无效")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Order_Failure_OutOfRange, "Order.Failure.OutOfRange", "命令失败：目标超出执行范围")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Order_Failure_InvalidRequest, "Order.Failure.InvalidRequest", "命令失败：请求数据无效")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Order_Failure_StaleCallback, "Order.Failure.StaleCallback", "命令失败：收到过期的异步回调")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Order_Failure_RetryExhausted, "Order.Failure.RetryExhausted", "命令失败：重试次数已经耗尽")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Attack_NotReady, "Combat.Failure.Attack.NotReady", "攻击失败：攻击间隔尚未完成")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Attack_Blocked, "Combat.Failure.Attack.Blocked", "攻击失败：单位状态禁止攻击")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Attack_StaleHandle, "Combat.Failure.Attack.StaleHandle", "攻击失败：攻击句柄已经失效")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Attack_Evaded, "Combat.Failure.Attack.Evaded", "攻击失败：目标闪避了本次攻击")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Projectile_StaleHandle, "Combat.Failure.Projectile.StaleHandle", "弹体失败：弹体句柄已经失效")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Projectile_Blocked, "Combat.Failure.Projectile.Blocked", "弹体失败：弹体被世界阻挡")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Projectile_TargetLost, "Combat.Failure.Projectile.TargetLost", "弹体失败：追踪目标已经丢失")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Projectile_Timeout, "Combat.Failure.Projectile.Timeout", "弹体失败：弹体生命周期超时")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Thinker_StaleHandle, "Combat.Failure.Thinker.StaleHandle", "Thinker 失败：句柄已经失效")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Motion_ChannelBusy, "Combat.Failure.Motion.ChannelBusy", "位移失败：指定 Motion 通道已被占用")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Motion_Blocked, "Combat.Failure.Motion.Blocked", "位移失败：移动路径被阻挡")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Motion_StaleHandle, "Combat.Failure.Motion.StaleHandle", "位移失败：Motion 句柄已经失效")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Ability_SpellBlocked, "Combat.Failure.Ability.SpellBlocked", "技能失败：技能被 SpellBlock 消耗并阻挡")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Modifier_DebuffImmune, "Combat.Failure.Modifier.DebuffImmune", "Modifier 失败：目标具有减益免疫")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Modifier_DispelImmune, "Combat.Failure.Modifier.DispelImmune", "Modifier 失败：目标具有驱散免疫")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Aura_StaleHandle, "Combat.Failure.Aura.StaleHandle", "Aura 失败：Aura 句柄已经失效")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Failure_Aura_Broken, "Combat.Failure.Aura.Broken", "Aura 失败：Owner 处于 Break 状态")

	UE_DEFINE_GAMEPLAY_TAG_COMMENT(RNG_Attack_Evasion, "Combat.RNG.Attack.Evasion", "普通攻击闪避使用的稳定随机域")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(RNG_Attack_Crit, "Combat.RNG.Attack.Crit", "普通攻击暴击使用的稳定随机域")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(RNG_Modifier_Proc, "Combat.RNG.Modifier.Proc", "Modifier 触发判定使用的稳定随机域")

	bool TryGetSingleDamageType(const FGameplayTagContainer& Tags, FGameplayTag& OutDamageType)
	{
		OutDamageType = FGameplayTag();
		const FGameplayTag DamageTypes[] = { Damage_Type_Physical, Damage_Type_Magical, Damage_Type_Pure };
		for (const FGameplayTag& DamageType : DamageTypes)
		{
			if (!Tags.HasTagExact(DamageType))
			{
				continue;
			}
			if (OutDamageType.IsValid())
			{
				OutDamageType = FGameplayTag();
				return false;
			}
			OutDamageType = DamageType;
		}
		return OutDamageType.IsValid();
	}
}
